# Generated by Django 2.2.6 on 2020-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Adult', models.IntegerField()),
                ('Child', models.IntegerField()),
            ],
        ),
    ]
